<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>promise</title>
  <script>
    // 2-1) 프로미스
    // "결과를 약속합니다!"
    // 예: (네트워크 요청 같은 시간이 좀 걸리는 로직을 통해) 데이터를 받아오면 그 때 네가 (then() 에) 등록한 콜백함수를 실행할 것을 약속할게
    // 비동기를 간편하게 처리할 수 있도록 도와주는 객체(콜백을 대체하여 비동기 처리 표준으로 쓰임)
    // 기능을 수행하고 나서 정상적으로 완료됐다면 처리된 결과값을 전달
    // 문제가 발생하면 에러를 전달해줌


    // 프로미스의 3가지 개념
    // 1) PromiseState - 프로미스 상태. 기능을 수행중인지, 완료됐는지(완료됐다면 성공인지 실패인지)에 대한 상태값
    // pending(프로미스가 만들어져서 기능을 수행중 일 때) -> fulfilled(성공적으로 다 끝내면) or rejected(예상치 못한 오류 발생 시)
    // resolve() 호출 시 fulfilled 상태로 바뀜
    // reject() 호출 시 recjected 상태로 바뀜

    // 2) PromiseResult - 프로미스 상태에 따른 결과
    // "상태" -> 결과
    // "pending" -> undefined
    // "fulfilled" -> 우리가 넘긴 결과값
    // "rejected" -> 일반적으로 Error 객체

    // 3) Producing code - 기능을 수행한 후 해당하는 데이터를 만들어내는 코드(시간이 걸릴 수 있는 코드) 
    //    Consuming code - 받은 데이터를 소비하는 코드(결과를 기다려야 하는 코드)
    // 프로미스는 "Producing code"와 "Consuming code"를 연결하고 최종 성공 또는 실패를 나타내는 객체

    // 프로미스 객체 만들기
    // 변수 = new Promise(콜백 함수);
    // 콜백 함수의 매개변수(resolve, reject) // 매개변수 명은 관례적으로 resolve와 reejct를 사용한다.
    // resolve(): 기능을 정상적으로 수행해서 최종 데이터를 전달하는 콜백 함수
    // reject(): 기능 수행 중 문제가 생기면 호출하게 될 콜백 함수

    // 프로미스 예제1:
    const myPromise = new Promise((resolve, reject) => {
      // Producing code 영역
      // 비동기적으로 수행하고 싶은 코드를 여기에 작성
      console.log('1.네트워크 요청 작업 또는 파일을 읽는 작업을 수행중...');
      // 프로미스 객체가 생성되고 바로 콜백함수가 실행됨!!
      
      const resultFlag = true; // 기능 수행 결과를 임의로 저장
      //const resultFlag = false; // 기능 수행 결과를 임의로 저장

      // 성공 시 resolve(), 실패 시 reject() 두 콜백 중 하나를 호출해야 함 
      setTimeout(() => {
        if(resultFlag) {
          resolve('2.기능 수행 후 얻은 데이터'); // 성공적으로 결과를 가져왔다면 resolve(PromiseResult*) 호출
        } else {
          reject(new Error('에러 발생!!')); // 실패했다면 reject(promiseResult**) 호출
        }
      }, 2000);
    });

    // Consuming code 영역
    myPromise // 메서드 채이닝으로 길어지기 때문에 가독성을 위해 .then을 아래에 입력
      .then((data) => { // 위에서 만든 프로미스가 정상적으로 잘 수행이 된다면(성공 시) then-그렇다면- data*를 받아와서 처리
        console.log(data);
      })
      .catch((err) => { // 위에서 만든 프로미스가 문제가 발생한다면(실패 시) err**를 잡아서 처리
        console.error(err);
      }); 

    // 정리:
    // 프로미스가 성공할 때의 값을 얻는 데 then()을 사용
    // 프로미스가 실패할 때의 오류를 처리하는데 catch()를 사용

    // 프로미스 예제2:
    // fetch()를 사용한 JSONPlaceholder API 사용
    // fetch()는 서버에서 리소스(결과, 데이터)를 가져오는 프로세스를 시작하고 그 결과로 프로미스를 반환
    // 성공 시 Response 객체를 받아 옴
    fetch('https://jsonplaceholder.typicode.com/posts') //서버에 리퀘스트 요청, 리스폰스가 응답으로 온다. fetch()의 결과는 promise 객체로 받아와진다
      .then((res) => { // fetch의 결과가 promise를 가져오므로 메서드채이닝 가능!
        console.log(res); // response 객체
        return res.json(); // response 객체의 json() 메소드: Response.body의 텍스트를 JSON으로 파싱(분석)한 결과를 가져옴
      }) // res.json()도 promise이므로 또 메서드 채이닝 가능
      .then(data => {
        console.log(data);
      });
      
      // (참고)
      // JSON 이란?
      // JavaScript Object Notation: 자바스크립트 객체 표기법
      // 자바스크립트 객체에서 영감을 받아 만들어진 표기법
      // 데이터를 저장하고 전송하기 위한 텍스트 포맷
      // { "key": "value" }

      // JSON의 특징
      // 심프라고 가벼운 데이터 교환 형식
      // 일반 텍스트 - 큰 따옴표 규격 사용
      // 데이터를 서버와 주고 받을 때 사용
      // 개발 언어에 독립적 - 모든 개발 언어에서 사용 가능하다

      const user = {
        name: 'goni',
        age: 33
      };
      console.log(user);
      const jsonUser = JSON.stringify(user); // 일반 자바스크립트 객체가 JSON규격으로 바뀌어짐
      console.log(jsonUser); 
      const objUser = JSON.parse(jsonUser); // JSON규격인 객체를 다시 일반 자바스크립트 객체로 바꾸어줌
      console.log(objUser);

    // 2-2) 프로미스promise 체이닝
    // 프로미스의 성공 또는 실패 여부와 무관하게
    // 이전 프로미스에서 반환된 것을 사용하여 프로미스를 계속 체이닝(연결) 할 수 있다.
    // 콜백 지옥보다 가독성이 좋고 간결

    // 프로미스 체이닝 예1:
    const myPromiseChain = new Promise((resolve, reject) => {
      resolve(); // 바로 성공시켜버리는 예제
    });

    myPromiseChain
      .then(data => {
        // 새로운 값을 반환
        console.log(data); // 프로미스에서 아무값도 넘겨주지 않았으므로 undefined
        return 'working...';
      })
      .then(data => { // 반환값(결과값)이 string이더라도 데이터타입은 프로미스객체로 인식됨 
        console.log(data);
        // throw 'failed'; // 보통 throw를 넘길 때는 에러객체를 만들어준다
        throw new Error('failed!'); // 에러값을 넘겨줄 때는 return 대신throw를 써서 catch로 받는다.
      })
      .catch(err => {
        // 프로미스 수행 중 발생한 오류를 받아서 출력
        console.error(err);
      });

    // 프로미스 체이닝 예2:
    // 실패한 경우에도 연결하여 사용할 수 있다.
    // catch() -> then()
    myPromiseChain
      .then(data => {
        throw new Error('ooops');//Uncaught (in promise) Error : 에러를 처리하는 것이 없으면 uncaught 에러가 발생됨 -> catch()를 뒤에 넣어줌으로 해결
        console.log('first value'); // log출력이 안되는 이유는? throw를 만나면 바로 멈추고 에러처리해서 catch()로 넘어가기 때문에 "throw 뒤에 코드 실행이 안됨"
      })
      .catch(err => {
        console.log('catched an error');
        return 'next value'; //에러 처리 후 return 반환값이 있으면 다음 then에 전달됨
      })
      .then (data => {
        console.log(data);
      });

    // 프로미스 체이닝 예3:
    // 콜백 지옥 예제2를 프로미스로 리팩토링 하기
    // 리팩토링이란? 기존코드를 개선해서 다시 만드는 행위


    // 콜백 지옥의 예2 리팩토링
    const loginUser = (id, password) => {
      return new Promise((resolve, reject) => {
        // 네트워크 통신을 하는 것처럼 꾸밈(setTimeout 쓴 이유)
        setTimeout(() => {
          if (id === 'goni' && password === '1234') {
            // 로그인과 관련된 작업을 하고 서버에서 받아온 유저 정보(여기서는 그냥 id)를 promise객체의 resolve함수에 전달
            resolve(id); 
          } else {
            reject(new Error('존재하지 않음'));
          }
        }, 2000);
      });
    };

    const getRoles = (userId) => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          if (userId === 'goni') {
            // 권한을 가져오는 작업을 하고 받아온 권한 정보를 promise객체의 resolve함수에 전달
            resolve({ name: 'JH Kim', role: 'admin' });
          } else {
            reject(new Error('접근 권한 없음'));
          }
        }, 1000);
      })
    };

    const id = prompt('아이디를 입력하세요.');
    const password = prompt('비밀번호를 입력하세요.');

    loginUser(id,password)
      .then(userID => { // 로그인이 성공하면 그러면
        return getRoles(userID); // userID 값을 통해 권한 정보를 얻는 getRoles()를 호출
      })
      .then(userInfo => { // 권한 정보를 얻어오면 그러면 alert창 띄움
        alert(`Welcome ${userInfo.name} (${userInfo.role})`);
      })
      .catch(err => { // 에러 핸들링 - 에러가 발생하면 catch해서 알려주겠다.
        console.error(err);
      })
    
    // 아래 과정을 간편하게 위로 대체
    // loginUser(id, password, userId => {
    //   // 로그인에 성공했다면 매개 변수로 받아온 userId를 이용하여 권한을 받아옴
    //   getRoles(userId, userInfo => {
    //     // 로그인에 성공 -> 사용자의 권한까지 잘 받아왔을 때
    //     alert(`Welcome ${userInfo.name} (${userInfo.role})`);
    //   }, error => {
    //     console.error(error);
    //   });
    // }, error => {
    //   console.error(error);
    // });
 

  </script>
</head>
<body>
  
</body>
</html>